/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2026;

import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author leiayuan
 */
public class HandlaggareFiltreradProjektStatus extends javax.swing.JFrame {
    private InfDB idb;
    private Integer aid;
     private Integer avdelningId;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HandlaggareFiltreradProjektStatus.class.getName());

    /**
     * Creates new form HandlaggareFiltreradProjektStatus
     */
    public HandlaggareFiltreradProjektStatus(InfDB idb, Integer aid) {
        this.idb = idb;
        this.aid = aid;
        initComponents();
        hamtaAvdelning();
        fyllTabell(null);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProjekt = new javax.swing.JTable();
        cbStatus = new javax.swing.JComboBox<>();
        btnFiltrera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProjekt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Projektnamn", "Startdatum", "Slutdatum", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblProjekt);

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj status", "Pågående", "Planerat", "Avslutat", " " }));
        cbStatus.addActionListener(this::cbStatusActionPerformed);

        btnFiltrera.setText("Filtrera");
        btnFiltrera.addActionListener(this::btnFiltreraActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnFiltrera)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrera))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void hamtaAvdelning() {
    try {
        String sql = "SELECT avdelning FROM anstalld WHERE aid = " + aid;
        avdelningId = Integer.parseInt(idb.fetchSingle(sql));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Kunde inte hämta avdelning");
    }
}
private void filtreraProjekt() {
    String status = cbStatus.getSelectedItem().toString();

    if (status.equals("Välj status")) {
        fyllTabell(null);
    } else {
        fyllTabell(status);
    }
}
private void fyllTabell(String status) {
    try {
        String sql =
            "SELECT projektnamn, startdatum, slutdatum, status " +
            "FROM projekt " +
            "WHERE avdelning = " + avdelningId;

        if (status != null) {
            sql += " AND status = '" + status + "'";
        }
var resultat = idb.fetchRows(sql);
        DefaultTableModel modell =
            (DefaultTableModel) tblProjekt.getModel();

        modell.setRowCount(0);

        for (var rad : resultat) {
            modell.addRow(new Object[] {
                rad.get("projektnamn"),
                rad.get("startdatum"),
                rad.get("slutdatum"),
                rad.get("status")
            });
        }

    } catch (InfException e) {
        JOptionPane.showMessageDialog(this, "Kunde inte hämta projekt");
    }}
    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    private void btnFiltreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltreraActionPerformed
        // TODO add your handling code here:
        filtreraProjekt();
    }//GEN-LAST:event_btnFiltreraActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrera;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProjekt;
    // End of variables declaration//GEN-END:variables
}

