/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2026;

import oru.inf.InfDB; 
import oru.inf.InfException;

/**
 *
 * @author leiayuan
 */
public class inloggning extends javax.swing.JFrame {
    private InfDB idb;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(inloggning.class.getName());

    /**
     * Creates new form inloggning
     */
    public inloggning(InfDB idb) {
        this.idb = idb;
        initComponents();
        lblFelmeddelande.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEpost = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        TfEpost = new javax.swing.JTextField();
        TfLosenord = new javax.swing.JTextField();
        lblFelmeddelande = new javax.swing.JLabel();
        btnLoggaIN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEpost.setText("E-post");

        lblLosenord.setText("Lösenord");

        TfEpost.addActionListener(this::TfEpostActionPerformed);

        lblFelmeddelande.setForeground(new java.awt.Color(255, 0, 0));
        lblFelmeddelande.setText("Felaktigt epost eller lösenord");

        btnLoggaIN.setText("Logga in");
        btnLoggaIN.addActionListener(this::btnLoggaINActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblLosenord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEpost, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFelmeddelande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TfEpost, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(TfLosenord))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoggaIN)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(TfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenord)
                    .addComponent(TfLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(lblFelmeddelande)
                .addGap(36, 36, 36)
                .addComponent(btnLoggaIN)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfEpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEpostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEpostActionPerformed

    private void btnLoggaINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaINActionPerformed
        String epost = TfEpost.getText();
        String losen = TfLosenord.getText();
        
   
        try {
        String sqlFraga =
        "SELECT losenord FROM anstalld WHERE epost = '" + epost + "'";

        String dbLosen = idb.fetchSingle(sqlFraga);

        if (dbLosen == null) {
            lblFelmeddelande.setVisible(true);
            return;
        }

        if (losen.equals(dbLosen)) {
String roll = null;

// kolla admin
if (idb.fetchSingle(
        "SELECT epost FROM admin WHERE epost = '" + epost + "'") != null) {
    roll = "ADMIN";
}
// kolla projektchef
else if (idb.fetchSingle(
        "SELECT epost FROM projektchef WHERE epost = '" + epost + "'") != null) {
    roll = "PROJEKTCHEF";
}
// annars handläggare
else if (idb.fetchSingle(
        "SELECT epost FROM handlaggare WHERE epost = '" + epost + "'") != null) {
    roll = "HANDLÄGGARE";
}
            

            String avdelning = idb.fetchSingle(
                "SELECT avdelning FROM anstalld WHERE epost = '" + epost + "'"
            );

            new Meny(idb, roll, epost, avdelning).setVisible(true);
            this.dispose(); // stäng loginfönstret

        } else {
            lblFelmeddelande.setVisible(true);
        }

    } catch (InfException ex) {
        System.out.println(ex.getMessage());
        lblFelmeddelande.setVisible(true);
    }


            
        
       
    }//GEN-LAST:event_btnLoggaINActionPerformed
 /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TfEpost;
    private javax.swing.JTextField TfLosenord;
    private javax.swing.JButton btnLoggaIN;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFelmeddelande;
    private javax.swing.JLabel lblLosenord;
    // End of variables declaration//GEN-END:variables
} 
