/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2026;

import oru.inf.InfDB; 
import oru.inf.InfException;

/**
 *
 * @author leiayuan
 */
public class Meny extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;

 
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Meny.class.getName());

    /**
     * Creates new form Meny
     */
    public Meny(InfDB idb, String epost ){
        this.inloggadAnvandare = epost;
        this.idb = idb;     
        initComponents();
        lblAnvandare.setText("Handläggare:" + epost);
        // Göm allt först
        btnMinaProjekt.setVisible(true);   
        btnProjektAvdelning.setVisible(true);
        btnFiltreraProjekt.setVisible(true);
        btnPartners.setVisible(true);
        btnHallbarhetsmal.setVisible(true);
        btnPersonalAvdelning.setVisible(true);
        btnSokHandlaggare.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnvandare = new javax.swing.JLabel();
        btnMinaUppgifter = new javax.swing.JButton();
        btnMinaProjekt = new javax.swing.JButton();
        btnProjektAvdelning = new javax.swing.JButton();
        btnFiltreraProjekt = new javax.swing.JButton();
        btnPartners = new javax.swing.JButton();
        btnHallbarhetsmal = new javax.swing.JButton();
        btnPersonalAvdelning = new javax.swing.JButton();
        btnSokHandlaggare = new javax.swing.JButton();
        btnLoggaUt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMinaUppgifter.setText("Mina uppgifter");
        btnMinaUppgifter.addActionListener(this::btnMinaUppgifterActionPerformed);

        btnMinaProjekt.setText("Mina projekt");

        btnProjektAvdelning.setText("Projekt på min avdelning");
        btnProjektAvdelning.addActionListener(this::btnProjektAvdelningActionPerformed);

        btnFiltreraProjekt.setText("Filtrera Projekt");

        btnPartners.setText("Partners");

        btnHallbarhetsmal.setText("Hållbarhetsmål");

        btnPersonalAvdelning.setText("Personal på min avdelning");

        btnSokHandlaggare.setText("Sök handläggare");

        btnLoggaUt.setText("Logga ut");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProjektAvdelning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSokHandlaggare))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPartners)
                            .addComponent(btnFiltreraProjekt))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHallbarhetsmal)
                    .addComponent(btnLoggaUt))
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMinaProjekt)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMinaUppgifter)
                                .addGap(39, 39, 39)
                                .addComponent(btnPersonalAvdelning)))
                        .addGap(0, 44, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnMinaUppgifter)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPersonalAvdelning)
                        .addGap(2, 2, 2)))
                .addComponent(btnMinaProjekt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProjektAvdelning)
                    .addComponent(btnSokHandlaggare))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFiltreraProjekt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnHallbarhetsmal)))
                .addGap(18, 18, 18)
                .addComponent(btnPartners)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoggaUt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinaUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaUppgifterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinaUppgifterActionPerformed

    private void btnProjektAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektAvdelningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProjektAvdelningActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltreraProjekt;
    private javax.swing.JButton btnHallbarhetsmal;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnMinaProjekt;
    private javax.swing.JButton btnMinaUppgifter;
    private javax.swing.JButton btnPartners;
    private javax.swing.JButton btnPersonalAvdelning;
    private javax.swing.JButton btnProjektAvdelning;
    private javax.swing.JButton btnSokHandlaggare;
    private javax.swing.JLabel lblAnvandare;
    // End of variables declaration//GEN-END:variables

}